image: python:3.x

stages:
  - test
  - deploy

variables:
  MYSQL_DATABASE: pharmatube
  MYSQL_USER: root
  MYSQL_PASSWORD: 
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  MYSQL_VERSION: '8.0'  # Specify the MySQL version you want to use

services:
  - mysql:${MYSQL_VERSION}

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python manage.py test

deploy:
  stage: deploy
  only:
    - master
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install -r requirements.txt
    - python manage.py migrate
    - python manage.py collectstatic --noinput
    - gunicorn your_project.wsgi:application -b 0.0.0.0:8000